### PR TITLE
Sync github with internal

### PR DESCRIPTION
**Pull request by DrTall**
We've been doing some development on our internal copy of the github client instead of on github. This diff reconciles that and then hopefully we will be better in the future.

Notably this diff removes the distributing producers which allow clients to specify which partitions to write to and makes the tests less racy.

### CODE REVIEW

**Comment by DrTall** [comment]
@zorkian PTAL. Not sure if I am doing this right. :)

**Comment by zorkian** [comment]
I think you're doing it right, but the tests should pass. Looks like the integration test, maybe go vet moved around?

**Comment by DrTall** [comment]
Yeah something definitely changed with `go vet`. Re-running the previously green build (master on Dropbox) now fails. So it's not this commit making it fail. Looking into it now...

**Comment by zorkian** [comment]
This has merge commits and stuff. Can you squash it down to a single commit? (And that will maybe make it rerun the build with the other PR landed.)

**Comment by DrTall** [comment]
PTAL @zorkian

**Pull request merged**
